### ISSUE TITLE
Update npm?

### ISSUE THREAD

**Issue by HaroldPutman** [jayproulx/vlt-watch#5]
The [package on npm](https://www.npmjs.com/package/vlt-watch) says it is 0.0.5, but the `package.json` here says 0.0.3 ? Can we get the latest code released to npm?

**Comment by jayproulx** [comment]
Sorry for the slow response, I was on vacation last week, just about caught up now.

Done https://www.npmjs.com/package/vlt-watch!

Not sure why it was 0.0.5 on npm, possibly some early growing pains, but I've updated package.json to 0.0.6 and published the new version.
