### ISSUE TITLE
Maybe better solution?

### ISSUE THREAD

**Issue by HaroldPutman** [jayproulx/vlt-watch#7]
While reading [the documentation for vlt](http://jackrabbit.apache.org/filevault/usage.html) I discovered there is a built in Vault Sync that does this same thing without any extra tooling.

```
cd /your/project/jrc_root
vlt sync
```
that folder is now magically kept in sync with your localhost jcr. And it works both directions. Only thing that needs to be running is AEM.

It also drops a file `.vlt-sync-config.properties` into the jcr_root folder that lets you turn syncing on and off at will.

![Facepalm](https://otvet.imgsmail.ru/download/544e98afd41ae6187e49b93799164def_i-389.jpg)

**Comment by jayproulx** [comment]
Whaaaaat?  This is news to me, but good news.  Thanks for passing that along!

**Comment by HaroldPutman** [comment]
vlt sync seems a little fragile. I managed to break it on my local instance, apparently beyond repair. So I am keeping vlt-watch around for daily use.
